### ISSUE TITLE
[Tracking] Develop a physical frame allocator under the memory subsystem

### ISSUE THREAD

**Issue by mdpcs3544** [charlotte-os/Catten-C#5]
Implement all of the following features.

- [ ] Read the Limine memory map and populate its own data structures to track usable and unusable page frames.
- [ ] Allocate a single frame
- [ ] Allocate n continguous frames
- [ ] Deallocate a single frame
- [ ] Deallocate a set of contiguous frames starting at a given physical address.
- [ ] Track frames that are committed but not actually allocated (such as those that might eventually be required by copy-on-write or faulted in virtual memory regions)
- [ ] For each allocated range of page frames track which virtual address spaces it is mapped into and which capabilites exist that could allow it to be mapped in the future. (Track these two things separately)
