### ISSUE TITLE
[Tracking] Create a proper GOP framebuffer driver to replace flanterm

### ISSUE THREAD

**Issue by mdpcs3544** [charlotte-os/Catten-C#6]
The framebuffer driver must provide the following features:

- [ ] Writing text to the framebuffer with its top left pixel at an arbitrary pixel location on the screen. This should take the font as a parameter.
- [ ] Drawing line segments
- [ ] Drawing basic shapes at arbitrary locations on the screen with color parameters for their borders and fill.
   - [ ] Triangle
   - [ ] Rectangle
   - [ ] Circle
   - [ ] Ellipse
- [ ] Draw any arbitrary bitmap image to the framebuffer in full color
- [ ] Double buffering
- [ ] Compositing multiple subsidiary framebuffers onto the back buffer

**Comment by mdpcs3544** [comment]
The old FB driver has been ported so this isn't needed.
